### ISSUE TITLE
Run issue

### ISSUE THREAD

**Issue by gongzelong0718** [TakWolf/Android-RefreshAndLoadMore-Demo#1]
无法编译运行，试过AS和命令行：
请问知道怎么解决吗？

Android Studio: 
Android Studio Koala | 2024.1.1 Patch 2
Build #AI-241.18034.62.2411.12169540, built on August 1, 2024
Runtime version: 17.0.11+0-17.0.11b1207.24-11852314 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.6.1
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 12
Metal Rendering is ON

```
9: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:mergeDebugNativeLibs'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.github.TakWolf.Android-InsetsWidget:insetswidget:0.0.1.
     Required by:
         project :app
      > Could not resolve com.github.TakWolf.Android-InsetsWidget:insetswidget:0.0.1.
         > Could not get resource 'https://jitpack.io/com/github/TakWolf/Android-InsetsWidget/insetswidget/0.0.1/insetswidget-0.0.1.module'.
            > Could not GET 'https://jitpack.io/com/github/TakWolf/Android-InsetsWidget/insetswidget/0.0.1/insetswidget-0.0.1.module'.
               > Read timed out
```

Command line: ./gradlew clean assembleDebug
```
> Task :app:dataBindingMergeDependencyArtifactsDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:dataBindingMergeDependencyArtifactsDebug'.
> Could not resolve all files for configuration ':app:debugCompileClasspath'.
   > Could not resolve com.github.TakWolf.Android-InsetsWidget:insetswidget:0.0.1.
     Required by:
         project :app
      > Skipped due to earlier error

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 1m 36s
3 actionable tasks: 2 executed, 1 up-to-date
```

**Comment by TakWolf** [comment]
https://github.com/TakWolf/Android-RefreshAndLoadMore-Demo/blob/master/settings.gradle.kts#L14 的 maven 仓库地址无法访问，可能需要魔法上网。


目前如下两个依赖发布于 jitpack.io，请检查下面的网址是否可以访问：

https://jitpack.io/#TakWolf/Android-HeaderAndFooterRecyclerView/0.0.7

https://jitpack.io/#TakWolf/Android-InsetsWidget/0.0.1

**Comment by gongzelong0718** [comment]
<img width="1490" alt="Screenshot 2024-08-19 at 21 15 44" src="https://github.com/user-attachments/assets/3f8476c8-6c61-41cc-bfff-c1f9a37d1ce2">
<img width="1418" alt="Screenshot 2024-08-19 at 21 16 06" src="https://github.com/user-attachments/assets/0f7b42a0-ee6d-4e83-8f98-dfc27b05b234">

浏览器看起来都是可以访问的

命令行添加了proxy还是不可以
```
➜  Android-RefreshAndLoadMore-Demo git:(master) export https_proxy=http://127.0.0.1:7890 http_proxy=http://127.0.0.1:7890 all_proxy=socks5://127.0.0.1:7890
➜  Android-RefreshAndLoadMore-Demo git:(master) ✗ ./gradlew clean assembleDebug
WARNING: We recommend using a newer Android Gradle plugin to use compileSdk = 35

This Android Gradle plugin (8.5.2) was tested up to compileSdk = 34.

You are strongly encouraged to update your project to use a newer
Android Gradle plugin that has been tested with compileSdk = 35.

If you are already using the latest version of the Android Gradle plugin,
you may need to wait until a newer version with support for compileSdk = 35 is available.

For more information refer to the compatibility table:
https://d.android.com/r/tools/api-level-support

To suppress this warning, add/update
    android.suppressUnsupportedCompileSdk=35
to this project's gradle.properties.
> Task :app:dataBindingMergeDependencyArtifactsDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:dataBindingMergeDependencyArtifactsDebug'.
> Could not resolve all files for configuration ':app:debugCompileClasspath'.
   > Could not resolve com.github.TakWolf.Android-InsetsWidget:insetswidget:0.0.1.
     Required by:
         project :app
      > Skipped due to earlier error

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 1m 42s
3 actionable tasks: 3 executed
```

很好奇您是用VPN魔法上网的吗？看起来魔法的招式还不同。求推荐同款。

**Comment by TakWolf** [comment]
Gradle 不走系统代理和环境参数代理，可以在 Android Studio 中设置代理，位置如下：
![QQ_1724073645991](https://github.com/user-attachments/assets/f5d8e88b-6f49-45ca-9c34-a1cffadc47a9)

或者手动配置代理： ~/.gradle/gradle.properties

```
systemProp.http.proxyHost=www.somehost.org
systemProp.http.proxyPort=8080
```

参考：https://docs.gradle.org/current/userguide/networking.html

**Comment by gongzelong0718** [comment]
我之前尝试过在Android Studio中配置代理，但是Check Connection那里一直显示connection reset。

但是在export了代码之后，又sync一下突然就可以了，此时在 Android Studio 中没设置代理，也没有手动配置代理：
<img width="1680" alt="Screenshot 2024-08-19 at 21 34 31" src="https://github.com/user-attachments/assets/59e05756-4222-4a2a-b039-546176fe1039">
<img width="1680" alt="Screenshot 2024-08-19 at 21 33 53" src="https://github.com/user-attachments/assets/9bf78bbc-c51e-4453-8e50-d2757fadd633">
<img width="1680" alt="Screenshot 2024-08-19 at 21 53 55" src="https://github.com/user-attachments/assets/c5a1c2c3-f12b-478a-8f26-2b93ed90f678">

```
➜  Android-RefreshAndLoadMore-Demo git:(master) ✗ cat ~/.gradle/gradle.properties
## For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html
#
# Specifies the JVM arguments used for the daemon process.
# The setting is particularly useful for tweaking memory settings.
# Default value: -Xmx1024m -XX:MaxPermSize=256m
# org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
#
# When configured, Gradle will run in incubating parallel mode.
# This option should only be used with decoupled projects. More details, visit
# http://www.gradle.org/docs/current/userguide/multi_project_builds.html#sec:decoupled_projects
# org.gradle.parallel=true
#Mon Dec 06 21:57:15 CST 2021
```


然后此时在 Android Studio 中设置代理，也可以Connection successful了。
<img width="1680" alt="Screenshot 2024-08-19 at 21 57 44" src="https://github.com/user-attachments/assets/5917d439-db0d-4a07-b1e7-f9a3b1ec2bb3">

**Comment by TakWolf** [comment]
目前能正常构建了吗？

**Comment by gongzelong0718** [comment]
之前sync的时候就可以构建了。

No Proxy - Read Time Out 
<img width="1680" alt="No Proxy - Read Time Out " src="https://github.com/user-attachments/assets/6cd64607-ec9e-41f7-ada4-e665530b7f74">



With Proxy - Connection Successful：
<img width="1680" alt="With Proxy - Connection Successful" src="https://github.com/user-attachments/assets/7fc10435-ee4a-4324-a25f-17234f9d53fc">


Connection test host
<img width="1680" alt="Connection test host" src="https://github.com/user-attachments/assets/8af865c0-ac60-4548-aaa6-d12d2fdcf033">

这么说是之前可以编译（构建）的原因可能是我尝试的时候Android Studio设置了代理。
与我操作了export https_proxy=http://127.0.0.1:7890 http_proxy=http://127.0.0.1:7890 all_proxy=socks5://127.0.0.1:7890不一定有关系。

**Comment by TakWolf** [comment]
android studio 和 gradle 代理配置实质上是给 jvm 设置代理。
jvm 是否走系统代理我也不确定，看你的情况也可能是走的。


另外，更改环境变量后，android studio 需要重启才能生效。
